### PR TITLE
Fix for Xcode 12

### LINKED ISSUE #139: XCode 12 Beta 6, compiler error
I was tying to build my project where I use RSBarcodes but I get a compiler error saying that: **Value of type 'AVMetadataMachineReadableCodeObject' has no member 'corners'**

It occurs on RSCodeReaderViewController.swift at line 401.

How can I fix it?

### PR DESCRIPTION
**Pull request by guykogus**
Fixes #139 
I also updated the library version as it bumps up the minimum OS requirement.

### CODE REVIEW

**Comment by marcuswu** [comment]
I'm not a maintainer here, but 👍 . This change does work for me and allows one of the legacy projects I work on to build and run in XCode 12.

**Comment by yeahdongcn** [comment]
🎉  Congrats

 🚀  RSBarcodes_Swift (5.1.0) successfully published
 📅  September 17th, 20:01
 🌎  https://cocoapods.org/pods/RSBarcodes_Swift
 👍  Tell your friends!

File: Source/RSCodeReaderViewController.swift [hunk 1]
```diff
@@ -178,15 +178,17 @@ open class RSCodeReaderViewController: UIViewController, AVCaptureMetadataOutput
 			self.output.setMetadataObjectsDelegate(self, queue: queue)
 		}
 		// Remove previous added outputs from session
-		var metadataObjectTypes: [AnyObject]?
+		var metadataObjectTypes: [AVMetadataObject.ObjectType]?
 		for output in self.session.outputs {
-			metadataObjectTypes = (output as AnyObject).metadataObjectTypes as [AnyObject]?
-			self.session.removeOutput(output )
+			if let output = output as? AVCaptureMetadataOutput {
+				metadataObjectTypes = output.metadataObjectTypes
```
Comment (shagedorn) [inline Source/RSCodeReaderViewController.swift:184]: I understand this was assigned previously as well, but wouldn't we want to append these objects to `metadataObjectTypes` instead? Otherwise, we can avoid the loop over the outputs (L182) and just use `self.session.outputs.last`.

Comment (guykogus) [reply Source/RSCodeReaderViewController.swift:184]: I was just cleaning the code, not the logic. Technically you're right, but it would be `self.session.outputs.last(where: { $0.metadataObjectTypes != nil })`. Since you're looping over all the outputs in order to remove them from the session I don't think you really lose anything by keeping it this way.

Comment (shagedorn) [reply Source/RSCodeReaderViewController.swift:184]: > I was just cleaning the code, not the logic.

I understand, sorry for dragging you into this 😅

Tbh, I'm not very familiar with AVFoundation so I don't know if it's expected to have more than one output with `metadataObjectTypes != nil`. I just saw the diff when updating our dependencies and stumbled over this, purely from a code/language perspective, and thought I'd raise it. If you (or someone else) is confident that this doesn't actually cause potential issues, feel free to close this conversation.

Comment (guykogus) [reply Source/RSCodeReaderViewController.swift:184]: Me neither. I'd say that until somebody raises an issue with this code don't worry too much about it 😅
